### ISSUE TITLE
Rotating around point

### ISSUE THREAD

**Issue by Jones-S** [jtnimoy/scripting-for-illustrator-tutorial#2]
Hi there

I enjoyed reading your tutorial, as the help for the scripting found online is very sparse. Anyway, I was wondering how I can rotate an object around a defined point (x/y). Until so far I only managed to rotate it with the given parameters:

```
Transformation:
Transformation.DOCUMENTORIGIN
Transformation.TOPLEFT
Transformation.LEFT
Transformation.BOTTOMLEFT
Transformation.TOP
Transformation.CENTER
Transformation.BOTTOM
Transformation.TOPRIGHT
Transformation.RIGHT
Transformation.BOTTOMRIGHT
```

Any help on that?
Thank you in advance.

**Comment by ThibaultJanBeyer** [comment]
No, there is not.
But a workaround would be to use DOCUMENTORIGIN.
- Move the object with the point you want to rotate to the document origin
- Rotate it around the document origin: `groups[j].rotate(60 * j, true, false, false, false, Transformation.DOCUMENTORIGIN);`

You can have a look at my script https://github.com/ThibaultJanBeyer/kaleidoscope-pattern-now.js where I did exactly this!

Make sure to show me your script when it is finished. Would love to see what you’re building :)

_Irrelevant side note: coding scripts for illustrator is a pain in the ass._

**Comment by Jones-S** [comment]
Hm. That sounds promising as well. I found another work around with some math:
I have this function which lets me calculate the x and y position of an object rotating with a specific radius around a center point.

```
var newCoordinates = calculatePosition(30, 100, {x: 0, y: 10});

function calculatePosition(angleInDegrees, radius, centerPoint){

    // Convert from degrees to radians via multiplication by PI/180
    var x = (radius * Math.cos(angleInDegrees * Math.PI / 180)) + centerPoint.x;
    var y = (radius * Math.sin(angleInDegrees * Math.PI / 180)) + centerPoint.y;

    return {x: x, y: y};
}
```

_And yes you are truly right about the pain in the ass. I had to open the script everytime in illustrator to see what happens and I don't have a logging function. And somehow the extendToolKit seems to crash when I run the code, but in Illustrator it's all good..._
